### ISSUE TITLE
CSS files are not live reloaded (fix included)

### ISSUE THREAD

**Issue by edge0703** [sparkbox/email-lab#3]
I just installed Email Lab and it works wonderful, thanks for all of your effort!

However I noticed that changes to SCSS files don't trigger LiveReload, although it's configured in Gruntfile.js - which is a bit tedious. After fiddling around a bit I found a quick fix. Within Grundfile.js, at "files" at the livereload config use '<%= config.src %>/scss/{,*/}*.scss' instead of '<%= config.tmp %>/css/{,*/}*.css

**Comment by nrambeck** [comment]
Thanks for the bug report and sorry for the late response to this. I'm not doing a good job of monitoring this projects issue queue. I created a pull request that resolves this LiveReload problem.
