### ISSUE TITLE
Error Message: unable to parse "settings.json" 

### ISSUE THREAD

**Issue by PHironaka** [sparkbox/email-lab#4]
I've successfully installed Grunt, Node & Bundler and followed steps 1-3 within my project's root directory.

After configuring my settings.json file, I entered 'Grunt Server' but got the following error message:

>> Error: Unable to parse "settings.json" file (Unexpected token “).
Warning: Task "server" not found. Use --force to continue.

Aborted due to warnings.

Does anyone know what could cause this?
Here's what my settings.json file looks like:

{
  "from": “Peter Hironaka <peterhironaka@mac.com>"
  "defaultTo": {
    "name": “Peter Hironaka“,
    "email": “peterhironaka@mac.com”
  },
  "transport": {
    "type": "SMTP",
    "options": {
      "service": “Gmail”,
      "auth": {
        "user": "peterhironaka@gmail.com",
        "pass": “xxxxxx“
      }
    }
  }
}

**Comment by nrambeck** [comment]
@PHironaka, There are 2 things I see wrong with the json. It's missing a comma after the "from" value. Also, many of your double quotes are not standard. Some of them are left/right double-quote characters. Copy/paste your json on this tool to clean it up.

http://jsonlint.com/

**Comment by bryanbraun** [comment]
Closing this for now, due to inactivity. If our suggestions didn't help then feel free to respond back. :+1:

**Comment by PHironaka** [comment]
@bryanbraun @nrambeck   sorry for the slow response guys. The suggestions worked, appreciate the help!
