### ISSUE TITLE
Characters being replaced with Unicode in media queries

### ISSUE THREAD

**Issue by judah-firewood** [sparkbox/email-lab#9]
Hi there,

Excellent tool! However, I'm running into an issue on build / send where characters in media queries are being replaced with their Unicode equivalent. This is great for HTML, but breaks css. (I realize this has nothing to do with the injection of inline-css which is one of my favorite features... this is in regards to media-queries targeting for specific platforms).

Example of CSS render in markup: '.inner > tbody' becomes '.inner &gt; tbody'

I've looked into grunt-premailer options, but to no avail. Any ideas how to turn this off (at least for CSS)?

Thanks for your time, and again, amazing tool!

Judah

**Comment by judah-firewood** [comment]
It seems my note above did the opposite of what I'm describing, lol. 

Example: > becomes & g t ;

**Comment by nrambeck** [comment]
hi @judah-firewood!

Not sure I understand how this is manifesting itself. Let's say you have:

```
.inner > tbody {
  color: #000;
}
```

It should inline the CSS like this in the HTML:

```
<div class="inner">
  ...
  <tbody style="color:#000;">
  ...
</div>
```

Where is the `.inner &gt; tbody` string getting added to the HTML?

**Comment by judah-firewood** [comment]
Correct, the inline-css works as you've described. However, I'm adding media queries which are getting added to the 'style' tag, just within the 'body' in the HTML.

**Comment by judah-firewood** [comment]
Same place that .ExternalClass and #backgroundTable can be found in the HTML of a build from project init.

**Comment by judah-firewood** [comment]
`<body leftmargin="0" topmargin="0" marginwidth="0" marginheight="0" style="-ms-text-size-adjust: none; -webkit-text-size-adjust: none; background: #f2f2f2; height: 100% !important; margin: 0; mso-line-height-rule: exactly; padding: 0; width: 100% !important" bgcolor="#f2f2f2"><style type="text/css">
body {
width: 100% !important; margin: 0; padding: 0; -webkit-text-size-adjust: 100%; -ms-text-size-adjust: 100%;
}
.ExternalClass {
width: 100%;
}
.ExternalClass {
line-height: 100%;
}
#backgroundTable {
width: 100% !important; margin: 0; padding: 0; line-height: 100% !important;
}
@media only screen and (max-width: 640px) {
  .inner &gt; tbody {
    display: block !important; max-width: 600px !important; width: 100% !important; height: auto !important;
  }
  .inner &gt; tbody &gt; tr {
    display: block !important; max-width: 600px !important; width: 100% !important; height: auto !important;
  }
  .inner &gt; tbody &gt; tr &gt; td {
    display: block !important; max-width: 600px !important; width: 100% !important; height: auto !important;
  }
}`

**Comment by judah-firewood** [comment]
Apologies for the formatting

**Comment by nrambeck** [comment]
Thanks for the rendered output example. I understand now. Also, I updated your code snippet to use triple backticks. That preserves your line-breaks. I'll look into it.

**Comment by judah-firewood** [comment]
Awesome, thanks!

**Comment by nrambeck** [comment]
@judah-firewood, I was able to replicate your problem. Unfortunately, I don't see an immediate solution. The source of the problem is Premailer. They encode the HTML and there isn't an option to prevent that. Also, they are moving the styles that can't be inlined (like your media query rules) inside of the `<body>` element instead of inside the `<head>` element. If they put it inside the head this encoding probably wouldn't happen. See [this issue](https://github.com/premailer/premailer/issues/141) with a similar complaint.

I'd recommend you post your problem in the [Premailer](https://github.com/premailer/premailer) issue queue. Also, consider rewriting your media query styles to prevent having to use the direct descendent selector which is being encoded.

Sorry, I couldn't be more helpful.

**Comment by judah-firewood** [comment]
No worries, that's where I ended up with the issue as well. I appreciate you taking the time to look into it! Have a great day. :)
